# Generated by Django 5.2.9 on 2026-03-17 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_avatar_alter_user_full_name_and_more'),
        ('vehicles', '0005_remove_vehicle_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='vehicles.vehicle'),
        ),
    ]
