server {
    listen 80;

    # Docker internal DNS resolver
    resolver 127.0.0.11 valid=30s;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $backend_upstream http://backend:8000;
        proxy_pass $backend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Static files for Django Admin
    location /static/Admin/ {
        set $backend_upstream http://backend:8000;
        proxy_pass $backend_upstream/static/Admin/;
    }

    # Media files
    location /media/ {
        set $backend_upstream http://backend:8000;
        proxy_pass $backend_upstream/media/;
    }
}
