# Generated by Django 5.2.9 on 2026-03-17 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_assigned_driver_remove_order_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='order',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
