# Generated by Django 5.2.9 on 2026-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='code',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_load',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_kg',
            field=models.IntegerField(default=0, help_text='Capacity in kg'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Volume in m3', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cost_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('motorcycle', 'Motorcycle')], default='truck', max_length=20),
        ),
    ]
