# Generated by Django 5.2.9 on 2026-03-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_plate_to_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
