# Generated by Django 5.2.9 on 2026-03-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_updated_at_alter_vehicle_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver_id',
        ),
    ]
