# Generated by Django 5.2.9 on 2026-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='order',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='route',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='driver_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='route',
            name='original_distance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unoptimized Distance in km', max_digits=10),
        ),
        migrations.AddField(
            model_name='route',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='warehouse_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='distance_from_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='routestop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='order_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='planned_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='time_from_previous',
            field=models.IntegerField(default=0, help_text='Time in minutes'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='warehouse_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance in km', max_digits=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_time',
            field=models.IntegerField(default=0, help_text='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='stop_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('warehouse', 'Warehouse')], default='delivery', max_length=20),
        ),
    ]
