# Generated by Django 5.2.9 on 2026-03-17 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_route_vehicle_remove_routestop_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='route',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
