# Generated by Django 5.2.9 on 2026-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='warehouse',
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='status',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lat',
            field=models.DecimalField(blank=True, db_column='lat', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='lng',
            field=models.DecimalField(blank=True, db_column='lng', decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='total_volume',
            field=models.IntegerField(default=0, help_text='Total volume capacity'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='used_volume',
            field=models.IntegerField(default=0, help_text='Used volume'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
