# Generated by Django 5.2.9 on 2026-03-10 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField()),
                ('order_code', models.CharField(max_length=50)),
                ('driver_id', models.UUIDField(blank=True, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('failed_pending', 'Failed - Pending Confirmation'), ('failed_confirmed', 'Failed - Confirmed')], default='pending', max_length=20)),
                ('proof_image', models.TextField(blank=True)),
                ('admin_confirmed', models.BooleanField(default=False)),
                ('admin_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
